"""comments

Revision ID: 11d43349dcbe
Revises: a3407be93806
Create Date: 2026-09-03 02:41:17.221702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d43349dcbe'
down_revision: Union[str, None] = 'a3407be93806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('project', 'milestone', 'update', 'file', name='commenttargettype'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_project', 'comments', ['project_id'], unique=False)
    op.create_index('ix_comments_target', 'comments', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###

    # Alembic does not autogenerate enum value additions — add them by hand.
    # Safe inside a transaction on PG 12+ so long as the new labels are not
    # used before commit.
    for label in ("COMMENT_ADDED", "COMMENT_REPLY"):
        op.execute(f"ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS '{label}'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_target', table_name='comments')
    op.drop_index('ix_comments_project', table_name='comments')
    op.drop_index('ix_comments_parent', table_name='comments')
    op.drop_table('comments')
    sa.Enum(name='commenttargettype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
    # Postgres cannot remove a value from an enum type, so the two
    # notificationtype labels added above are left in place on downgrade.
