"""engagements

Revision ID: d871ef6197db
Revises: 60afbf0e72f0
Create Date: 2026-09-11 00:59:40.146594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd871ef6197db'
down_revision: Union[str, None] = '60afbf0e72f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('agreement_title', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('revision_policy', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('additional_terms', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_by', sa.String(), nullable=True),
    sa.Column('agreement_hash', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by', sa.String(), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signer_title', sa.String(length=255), nullable=True),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signer_ip', sa.String(length=64), nullable=True),
    sa.Column('signer_user_agent', sa.String(length=500), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('invoice_due_date', sa.Date(), nullable=True),
    sa.Column('invoice_notes', sa.Text(), nullable=True),
    sa.Column('stripe_payment_url', sa.String(length=500), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('payment_reported_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reported_by', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_channel', sa.String(length=255), nullable=True),
    sa.Column('response_time', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.String(length=255), nullable=True),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.Column('welcome_read_at', sa.DateTime(), nullable=True),
    sa.Column('call_booking_url', sa.String(length=500), nullable=True),
    sa.Column('call_agenda', sa.JSON(), nullable=True),
    sa.Column('call_scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('call_prep_notes', sa.Text(), nullable=True),
    sa.Column('call_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagements')
    # ### end Alembic commands ###
